### ISSUE TITLE
Display/Indicate currently selected filament

### ISSUE THREAD

**Issue by ururk** [Printrbot/Printrhub#14]
After switching filament types (PLA -> Ninjaflex), there is no indication what filament type is being printed with. Some ideas:

* Green check mark indicating a specific filament is selected as the current material
* On the printing screen, indicate which filament is selected
* On the filament picker screen, have the first choice be the selected filament type and use the words "Current Filament"
* A persistent "Material: Name" on relevant screens (load/unload, print, etc...)

I've been switching between a few different filament types, and think it would be useful to know what filament the printer currently thinks it is using. Also, I'm guessing it always reverts to the first filament in the list after rebooting, but I don't actually know.

**Comment by mickbalaban** [comment]
Added "selected" message instead of select button on material screen when current filament is displayed.  Also added material message to the print status scene (replacing inaccurate time estimate)

https://github.com/Printrbot/Printrhub/commit/fc4516317c4d3a1840bdff1b44222dd81d090bee
https://github.com/Printrbot/Printrhub/commit/f8f0ae3401f5a255a8c80860f8724f0b174dc480
